[package]
name = "mcs"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.31"
clap = { version = "4.4.14", features = ["derive"] }
home = "0.5.9"
indicatif = "0.17.7"
lazy_static = "1.4.0"
reqwest = { version = "0.11.23", features = ["blocking"] }
serde_json = "1.0.111"
