[package]
name = "mcs"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.24"
clap = { version = "4.1.9", features = ["derive"] }
home = "0.5.4"
lazy_static = "1.4.0"
reqwest = { version = "0.11.14", features = ["blocking"] }
serde_json = "1.0.94"
